### PR TITLE
assimp-rs link does not work

### PR DESCRIPTION
**Pull request by Sollimann**
Changed the assimp-rs link as the current one didn't work

### CODE REVIEW

**Comment by OTL** [comment]
The link is not working actually!!
But your fix is not correct. I'm using assimp version 0.3.1.
And I can't find the correct source now!

**Comment by OTL** [comment]
I googled and found that https://github.com/Vurich/assimp-rs is the successor of assimp-rs and the name has been changed to open-asset-importer for crates.io.

**Comment by Sollimann** [comment]
@OTL Okey, I see. Changed it to the successor you referenced.

**Comment by OTL** [comment]
🙏🙏🙏

**Comment by Sollimann** [comment]
@OTL any more changes needed?

**Comment by OTL** [comment]
Thanks!

**Pull request merged**
